### ISSUE TITLE
Launch pages with arguments

### ISSUE THREAD

**Issue by mywaystar** [cobaltians/Cobalt#30]
It's could be awesome to launch a cobalt view with arguments, like intents with Extra options on Android.

I think it can be done. You are experts, alright?

**Comment by ggendre** [comment]
Yes, I agree ! and yes we are experts ;)

I think of such functionality since the beginnings of the framework. 
It's quite simple to add :
* add an object in the push command
* store it in storage
* retrieve it in the [onPageShown event](https://github.com/cobaltians/cobalt/wiki/Cobalt-Web-Lifecycle-Events)

I hope to implement this for the 0.4 or 0.5 release.

**Comment by ggendre** [comment]
Done in Cobalt 0.4.1 (release in progress, stay tuned)
