### ISSUE TITLE
Remove the DatePicker form the Cobalt Core

### ISSUE THREAD

**Issue by baptistejamin** [cobaltians/Cobalt#32]
Like other Pickers, make DatePicker available as a plugin.

**Comment by ggendre** [comment]
Finally, I agree : All Android pickers (Date, time, Datetime, weeks, months) will have to move in a single android-only plugin

**Comment by ggendre** [comment]
Question is : What do we do of the small iOS code.
There is a small JS code to fix the placeholder for iOS because it was not displayed (at the time, it was iOS7 I suppose). 
Will try to remove it and see if it's fixed on iOS 8

**Comment by mywaystar** [comment]
Each plugin should have a js/Android /iOS sources. It can work

-----Message d'origine-----
De : "Guillaume Gendre" <notifications@github.com>
Envoyé : ‎11/‎05/‎2015 14:05
À : "cobaltians/cobalt" <cobalt@noreply.github.com>
Cc : "Baptiste JAMIN" <baptistejamin@gmail.com>
Objet : Re: [cobalt] Remove the DatePicker form the Cobalt Core (#32)

Question is : What do we do of the small iOS code.
There is a small JS code to fix the placeholder for iOS because it was not displayed (at the time, it was iOS7 I suppose). 
Will try to remove it and see if it's fixed on iOS 8

**Comment by ggendre** [comment]
https://github.com/cobaltians/Cobalt/issues/170
