### ISSUE TITLE
fix JavaBridge issues

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#83]
Find why there is javaBridge issues sometimes on Android.

try to send every messages for the webview in this JavaBridge thread.

- [x] iOS: check that messages received which need UI update or dispatch are excecuted in the main thread.
- [x] Android: check that messages received which need UI update or dispatch are excecuted in the UiThread.
- [x] Android: check that messages sent are executed in the UiThread.
- [x] iOS: check that messages sent are executed in the main thread.

**Comment by Doc1faux** [comment]
As explained [here](https://developer.android.com/guide/webapps/migrating.html#Threads), messages to the WebView have to be sent from the UiThread and this is already the case.

@Myrdhinn was overdoing it a bit in the `executeScriptInWebView` method.

But all messages from the WebView are received from the JavaBridge thread.
For each event catched in the `onCobaltMessage` which need UI update or are dispatched to the classes of the Cobalt user, we need to switch to the UiThread.

**Comment by Doc1faux** [comment]
For iOS, `onCobaltMessage` method returns NO to the Web for unhandled messages/events/callbacks dispatched to user classes and plugins because we cannot send them synchronously to the MainThread without blocking the whole app (see https://stackoverflow.com/questions/5316154/what-is-the-web-thread#answer-5316246)
