### ISSUE TITLE
nativeBars - iOS icon centering

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#94]
When using fontAwesome for example, it occurs that the font icon is not centered into the space reserved for the icon. So alignment is not perfect.

And, related I suppose, when using a large icon like `fa-cloud` the cloud is cropped (there is a sample of this in the Catalog I think)

**Comment by Doc1faux** [comment]
For the horizontal alignement problem, it appears that it is the way how no-badged-action are instantiated which create this illusion of not-well-horizontally-centered-icon in action effect because their width are not equals to the handmade ones...

**Comment by Doc1faux** [comment]
After checking, it appears that the horizontal alignment difference is less than 2% (0 to 4px range for 220px space) for a same kind of icon.

See below the content and whiteframe captures for the cloud icon from an asset and generated with FontAwesome, with and whitout a badge.

![content](https://cloud.githubusercontent.com/assets/2175246/17329086/477f3e44-58c1-11e6-94d3-91ff821fb6c4.png)
![whiteframe](https://cloud.githubusercontent.com/assets/2175246/17329088/491850d8-58c1-11e6-88b7-e4ff3c998c14.png)

**Comment by Doc1faux** [comment]
For the crop issue that we are still facing, it appears that it is the [fontToCobalt](https://github.com/Cobaltians-Fonts/fontToCobalt) script which is missing some entries while parsing the CSS file.

For example, for the CSS classes below, extracted from the CSS file provided by FontAwesome, the only remaining class in the glyph dictionary in the iOS class is the first `.fa-flash` one.

```
.fa-flash:before,
.fa-bolt:before {
  content: "\f0e7";
}
```

So it results in an empty image because this specific case is not handled on iOS.

**Comment by Doc1faux** [comment]
Finally, the case was handled on iOS, but after many tests, I have found that the title was cropped if the action has a badge. Fixed by the last commit.

**Comment by Doc1faux** [comment]
After [this test](https://github.com/cobaltians/Cobalt/issues/96#issuecomment-237201110) for issue #96, I saw the horizontal alignement problem and I thought it was due to actions with text and I was right!

See below the screenshot of an app made with only system icons (text and icon)

![native](https://cloud.githubusercontent.com/assets/2175246/17363353/2c0a26ce-597a-11e6-96f4-b8b66333c775.png)

Text buttons have no padding while icon buttons does.

**Comment by ggendre** [comment]
sorry, assigned back because it is not ok in top bar.

**Comment by Doc1faux** [comment]
And if you just missed to update the Catalog on the latest Cobalt version?
Seems fine to me...

![screen shot 2016-08-18 at 17 54 24](https://cloud.githubusercontent.com/assets/2175246/17780790/f20922e6-656c-11e6-87f9-31ac2d6bdda1.png)

**Comment by ggendre** [comment]
works well. good job. closing :)
