### ISSUE TITLE
nativeBars - iOS icon vertical alignment

### ISSUE THREAD

**Issue by ggendre** [cobaltians/Cobalt#96]
vertical alignment is not perfect when mixing font icon and real asset icon.

Try it in the Catalog Sample and you will see.

**Comment by Doc1faux** [comment]
After checking it, it seems that icons are vertical centers (see screenshot below)
@ggendre Is that not what we were looking for?

![img_0006](https://cloud.githubusercontent.com/assets/2175246/17328047/b84fd210-58bb-11e6-99a4-b3abfbe0031b.jpg)

_Note: real asset icons are the following ones, the others are the FontAwesome ones_

![sun 2x](https://cloud.githubusercontent.com/assets/2175246/17328077/e247873e-58bb-11e6-95d0-d49ae0137395.png) ![cloudy 2x](https://cloud.githubusercontent.com/assets/2175246/17328076/e247567e-58bb-11e6-95e1-f0a80e498c11.png)

**Comment by Doc1faux** [comment]
While I was debugging the crop issue (see issue [#94](https://github.com/cobaltians/Cobalt/issues/94#issuecomment-236904022)) due to the fontToCobalt script, I replaced the missing `fa-bolt` character with the `fa-arrows-v` one and I saw an y-offset between an action with a badge (made with a customView) and an other without one (made with the system component) but with the same icon (see content and whiteframe captures below).

![content](https://cloud.githubusercontent.com/assets/2175246/17332970/eb334b48-58d0-11e6-8e3a-20cad344240c.png)
![whiteframe](https://cloud.githubusercontent.com/assets/2175246/17332971/ed94bbba-58d0-11e6-838e-4378588475e5.png)

However, it is the one made with the customView which is correctly centered in the bar, so I do not know how to fix this issue without being crappy :/

**Comment by Doc1faux** [comment]
What is weird is that this offset is more marked in the top bar than in the bottom bar (see below)

### Top bar

![top-content](https://cloud.githubusercontent.com/assets/2175246/17362419/563ef136-5975-11e6-887d-cbd7ad371239.png)
![top-whiteframe](https://cloud.githubusercontent.com/assets/2175246/17362432/618c793c-5975-11e6-8727-cff222d887fa.png)

### Bottom bar

![bottom-content](https://cloud.githubusercontent.com/assets/2175246/17362444/6b5a6e7e-5975-11e6-93b6-090b99fcdd04.png)
![bottom-whiteframe](https://cloud.githubusercontent.com/assets/2175246/17362446/6c769ff8-5975-11e6-8d44-6676e84e19e4.png)
